apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
bases:
  - ../../base/build
  - ../../base/jenkins
  - ../../base/nexus2
  - ../../base/sonarqube
resources:
  - quay-cicd-sealedsecret.json
  - quay-creds-sealedsecret.json
